#!/bin/python3
from fsrs import Card, FSRS, Rating
import datetime
import argparse
import pickle
import os

DB_NAME = f'{os.getenv("DOC2")}/fsrs.db'


def _load_db():
    if not os.path.exists(DB_NAME):
        return {}
    with open(DB_NAME, 'rb') as f:
        try:
            db = pickle.load(f)
        except EOFError:
            return {}
    return db


def list_cards():
    db = _load_db()
    for (file, card) in db.items():
        if card.due.date() - datetime.timedelta(days=6) <= datetime.datetime.now().date():
            print(file, f'\033[36m{card.due.date()}\033[0m')


def delete_card(file):
    db = _load_db()

    with open(DB_NAME, 'wb+') as f:
        file = os.path.abspath(file)
        try:
            del db[file]
        except KeyError:
            print(f'No such file in database: {file}')
        else:
            pickle.dump(db, f)
            print(f'Deleted {file} from database.')


def _update_card(card: Card) -> Card:
    f = FSRS()
    scheduled_cards = f.repeat(card, datetime.datetime.now())
    return scheduled_cards[Rating.Easy].card


def update_card(file):
    if not os.path.exists(file):
        print(f'No such file: {file}')
        return

    file = os.path.abspath(file)
    db = _load_db()
    with open(DB_NAME, 'wb+') as f:
        try:
            c = db[file]
        except KeyError:
            c = Card()
        c = _update_card(c)
        db[file] = c
        pickle.dump(db, f)


if __name__ == '__main__':
    arg_parser = argparse.ArgumentParser()
    arg_parser.description = 'DB path: $DOC2/fsrs.db'
    arg_parser.add_argument('-d', '--delete', action='store_true',
                            help='Delete the card from the database')
    arg_parser.add_argument('file', type=str, metavar='FILE',
                            nargs='?', help='The file to be schedule')
    args = arg_parser.parse_args()
    if args.file:
        if args.delete:
            delete_card(args.file)
        else:
            update_card(args.file)
    else:
        list_cards()
