#!/bin/bash

case $1 in
	dblp)
		echo 'Download the bibtex file from dblp'
		echo 'See: https://github.com/jiangyinzuo/dblp-api/tree/dev'
		;;
	genproj)
		echo 'Generate .project.vim'
		;;
	start)
		echo 'alias of cmd.exe /C start ""'
		echo 'Open a file or a directory in Windows'
		;;
	mklink|mklinkd)
		echo 'mklink: make a symbolic link to a file'
		echo 'mklinkd: make a symbolic link to a directory'
		;;
	z)
		echo 'cd to the most recently used directory matching the pattern'
		echo 'See: https://github.com/rupa/z'
		;;
	zt)
		echo '根据最近cd时间排序目录，并通过fzf cd目录, 依赖z'
		;;
	bd)
		echo 'cd到某个父目录。bd是一个bash function，依赖真正的bd'
		echo 'See: https://github.com/vigneshwaranr/bd'
		;;
	*)
		echo 'Usage: wslhelp [command/scripts]'
		echo
		echo 'Commands are sourced in bashrc'
		echo "Scripts are stored at $VIMRC_ROOT/scripts/"
		echo "See also: $BASH_SOURCE"
		;;
esac

