#!/bin/bash

set -o vi

. ~/vimrc/root/z.sh

alias start='cmd.exe /C start ""'

# cmd.exe /c mklink /d parameter_server  "D:\doc2\cs\aisys\parameter_server"
mklinkd() {
	if [ $# -eq 2 ]; then
		target=$2
		target=${target/\/mnt\/d/D:}
		target=${target//\//\\}
		echo 'create link: ' $1 ' target: ' $target
		cmd.exe /c mklink /d $1 $target
	elif [ $# -eq 1 ]; then
		# mklinkd /mnt/d/doc2/cs/aisys
		target=$1
		link=${target##*/} # link = "aisys"
		target=${target/\/mnt\/d/D:}
		echo $target
		target=${target//\//\\}
		echo 'create link: ' $link ' target: ' $target
		cmd.exe /c mklink /d $link $target
	fi
}

alias vimt='vim --servername TEX'
alias vimhelp='vim -c ":Lines!" ~/.vim/doc/mydoc.txt'

source ~/vimrc/root/fzf/fzf.bash
source ~/vimrc/root/vimdf

# 还有rga
# https://github.com/phiresky/ripgrep-all

alias rgpipe='~/vimrc/root/rgpipe'
RGPIPE='~/vimrc/root/rgpipe'
alias rgi="rg -i -z --max-columns-preview --max-columns 500 --hidden --no-ignore --pre-glob \
	'*.{pdf,xl[tas][bxm],xl[wsrta],do[ct],do[ct][xm],p[po]t[xm],p[op]t,html,htm,xhtm,xhtml,epub,chm,od[stp]}' --pre ${RGPIPE}"

export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"

if [[ `uname -a` == *WSL* ]]; then
	. ~/vimrc/root/wsl-init.bash
fi
