#!/bin/bash

set -o vi

. ~/vimrc/root/z.sh

alias start='cmd.exe /C start ""'

# cmd.exe /c mklink /d parameter_server  "D:\doc2\cs\aisys\parameter_server"
mklinkd() {
	str=$2
	str=${str/\/mnt\/d/D:}
	str=${str//\//\\}
	echo $str
	cmd.exe /c mklink /d $1 $str
}

alias vimt='vim --servername TEX'
alias vimhelp='vim -c ":Lines!" ~/.vim/doc/mydoc.txt'

source ~/vimrc/root/fzf/fzf.bash
source ~/vimrc/root/vimdf

alias rgpipe='~/vimrc/root/rgpipe'
RGPIPE='~/vimrc/root/rgpipe'
alias rgi="rg -i -z --max-columns-preview --max-columns 500 --hidden --no-ignore --pre-glob \
	'*.{pdf,xl[tas][bxm],xl[wsrta],do[ct],do[ct][xm],p[po]t[xm],p[op]t,html,htm,xhtm,xhtml,epub,chm,od[stp]}' --pre ${RGPIPE}"

export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"
