command -nargs=0 DiffThisBufferFirst call diffbuffer#SaveTempFile()
" diff, delta, ...
command -nargs=? -complete=custom,diffbuffer#ExternalToolsComplete DiffThisBufferSecond if len(<q-args>) == 0 | call diffbuffer#Diff() | else | call diffbuffer#DiffExternal(<f-args>) | endif
