#!/bin/bash

DB=$DOC2/daily/daily.sqlite3

usage() {
	echo "DB: $DB"
	echo "Usage:"
	echo "       $0 -h" 
	echo "       $0 db"
	echo "       $0 getup|sleep [time]"
	echo "       $0 done comment..."
	echo "       $0 todo comment..."
	echo "       $0 todo -d id"
	exit 1
}

if [[ $# -eq 0 ]]; then
	sqlite3 -echo $DB "
		select 'getup';
		select * from getup order by date desc limit 7;
		select 'sleep';
		select * from sleep order by date desc limit 7;
		select 'done';
		select * from done where date >= date('now', 'localtime', '-7 days') order by date desc;
		select 'todo';
		select * from todo;
	"
	exit 0
fi

while [[ $# -gt 0 ]]; do
	case $1 in
		-h)
			usage
			;;
		db)
			sqlite3 $DB
			exit $?
			;;
		getup|sleep)
			if [[ $1 == "getup" ]]; then
				d="strftime('%Y-%m-%d', 'now', 'localtime')"
			else
				d="strftime('%Y-%m-%d', datetime('now', 'localtime', '-1 days'))"
			fi
			if [[ $# == 2 ]]; then
				if [[ $2 =~ ^[0-9]{2}:[0-9]{2}$ ]]; then
					sqlite3 -echo $DB "insert into $1 values($d, '$2');"
					exit 0
				else
					echo "Invalid time format: $2"
					exit 1
				fi
			elif [[ $# == 1 ]]; then
				sqlite3 -echo $DB "insert into $1 values($d, strftime('%H:%M', 'now', 'localtime'));"
			fi
			exit 0
			;;
		done)
			shift
			if [[ $# -eq 0 ]]; then
				usage
			fi
			if [[ $# == 1 && $1 =~ ^[0-9]+$ ]]; then
				# move todo to done
				sqlite3 -echo $DB "
				insert into done select date('now', 'localtime'), comment from todo where id = $1;
				delete from todo where id = $1;
				"
				exit 0
			fi
			sqlite3 -echo $DB "insert into done values(strftime('%Y-%m-%d', 'now', 'localtime'), '$*');"
			exit 0
			;;
		todo)
			shift
			if [[ $# -eq 0 ]]; then
				usage
			fi
			if [[ $1 == '-d' ]]; then
				if [[ $# -ne 2 ]]; then
					usage
				fi
				sqlite3 -echo $DB "delete from todo where id = $2;"
			else
				sqlite3 -echo $DB "insert into todo(comment) values('$*');"
			fi
			exit 0
			;;
		*)
			usage
			;;
	esac
done

usage
