#!/bin/python3
from fsrs import Card, FSRS, Rating
import datetime
import argparse
import pickle
import os

DB_NAME = f'{os.getenv("DOC2")}/fsrs.db'

def list_cards():
    if not os.path.exists(DB_NAME):
        return
    with open(DB_NAME, 'rb') as f:
        db = pickle.load(f)
    for (file, card) in db.items():
        if card.scheduled_days <= 6:
            print(file, card.scheduled_days, sep='\t')


def delete_card(file):
    if not os.path.exists(DB_NAME):
        print('Database is empty.')
        return
    with open(DB_NAME, 'rb') as f:
        db = pickle.load(f)
    with open(DB_NAME, 'wb+') as f:
        try:
            del db[file]
            pickle.dump(db, f)
        except KeyError:
            print(f'No such file in database: {file}')
        else:
            print(f'Deleted {file} from database.')


def _update_card(card: Card) -> Card:
    f = FSRS()
    scheduled_cards = f.repeat(card, datetime.datetime.now())
    return scheduled_cards[Rating.Easy].card


def update_card(file):
    file = os.path.abspath(file)
    if not os.path.exists(DB_NAME):
        db = {}
    else:
        with open(DB_NAME, 'rb') as f:
            db = pickle.load(f)
    with open(DB_NAME, 'wb+') as f:
        try:
            c = db[file]
        except KeyError:
            c = Card()
        c = _update_card(c)
        db[file] = c
        pickle.dump(db, f)


if __name__ == '__main__':
    arg_parser = argparse.ArgumentParser()
    arg_parser.description = 'DB path: $DOC2/fsrs.db'
    arg_parser.add_argument('-d', '--delete', action='store_true',
                            help='Delete the card from the database')
    arg_parser.add_argument('file', type=str, metavar='FILE',
                            nargs='?', help='The file to be schedule')
    args = arg_parser.parse_args()
    if args.file:
        if args.delete:
            delete_card(args.file)
        else:
            update_card(args.file)
    else:
        list_cards()
