name: load_vimrc

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  load_vimrc_in_vim7_4:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: single vimrc with vim.tiny
      run: vim.tiny -E -s -u .vimrc -c "qa!"
    - name: install vim
      # CentOS 7.1 uses Vim 7.4.629
      run: sudo ./install/build_vim.sh v7.4.629
    - name: single vimrc
      run: vim -E -s -u .vimrc -c "qa!"
    - name: single vimrc with view
      run: vim -R -E -s -u .vimrc -c "qa!"
    - name: full vimrc
      run: ln -s `pwd`/root/.vim ~/.vim && vim -E -s -c "qa!"
    - name: full vimrc with vim.tiny
      run: vim.tiny -E -s -c "qa!"
    - name: full vimrc with view
      run: vim -R -E -s -c "qa!"
  load_vimrc_in_latest_vim:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: single vimrc with vim.tiny
      run: vim.tiny -E -s -u .vimrc -c "qa!"
    - name: install X11
      run: sudo apt update && sudo apt install -y libx11-dev xorg-dev
    - name: install vim
      run: sudo ./install/build_vim.sh
    - name: single vimrc
      run: vim -E -s -u .vimrc -c "qa!"
    - name: single vimrc with view
      run: vim -R -E -s -u .vimrc -c "qa!"
    - name: full vimrc
      run: ln -s `pwd`/root/.vim ~/.vim && vim -E -s -c "qa!"
    - name: full vimrc with vim.tiny
      run: vim.tiny -E -s -c "qa!"
    - name: full vimrc with view
      run: vim -R -E -s -c "qa!"
    - name: vim noplugin
      run: vim --noplugin -E -s -c "qa!"
    - name: vim -u NONE
      run: vim -u NONE -E -s -c "qa!"
    - name: vim -u NORC
      run: vim -u NORC -E -s -c "qa!"
    - name: vim -u DEFAULTS
      run: vim -u DEFAULTS -E -s -c "qa!"
